# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_level',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
